import uuid
from fastapi import APIRouter, Depends, HTTPException, status, Response, Body
from sqlalchemy.orm import Session
from typing import List
from backend.app.database.connection import get_db
from backend.app.models.paper import GeneratedPaper
from backend.app.models.academic import Board, Class, Subject, Chapter
from backend.app.schemas.paper import PaperGenerateRequest, PaperOut
from backend.app.services.rag_service import rag_service
from backend.app.services.gemini_service import gemini_service
from backend.app.services.pdf_service import pdf_service
from backend.app.utils.security import get_current_user
from backend.app.models.user import User

router = APIRouter(prefix="/papers", tags=["Question Papers"])

@router.get("/", response_model=List[PaperOut])
def get_saved_papers(
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Retrieve all saved question papers generated by the user."""
    return db.query(GeneratedPaper).filter(
        GeneratedPaper.created_by == current_user.id
    ).order_by(GeneratedPaper.created_at.desc()).all()

@router.get("/{paper_id}", response_model=PaperOut)
def get_paper_by_id(
    paper_id: str, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Retrieve detailed JSON configuration of a saved paper."""
    paper = db.query(GeneratedPaper).filter(GeneratedPaper.id == paper_id).first()
    if not paper:
        raise HTTPException(status_code=404, detail="Question paper not found.")
    return paper

@router.post("/", response_model=PaperOut, status_code=status.HTTP_201_CREATED)
def generate_ai_paper(
    req: PaperGenerateRequest, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Uses pgvector semantic retrieval and Google Gemini Flash to generate a balanced multi-set exam paper."""
    # 1. Fetch academic names
    board = db.query(Board).filter(Board.id == req.board_id).first()
    classroom = db.query(Class).filter(Class.id == req.class_id).first()
    subject = db.query(Subject).filter(Subject.id == req.subject_id).first()
    chapters = db.query(Chapter).filter(Chapter.id.in_(req.chapter_ids)).all()
    
    if not (board and classroom and subject and chapters):
        raise HTTPException(
            status_code=400, 
            detail="Invalid board, class, subject, or chapter selection."
        )

    chapter_names = [ch.chapter_name for ch in chapters]

    # 2. Call Gemini API to generate paper
    total_marks = req.total_marks
    if req.question_breakdown:
        total_marks = sum(int(m) * count for m, count in req.question_breakdown.items() if count > 0)

    difficulty_dist = {
        "easy": req.easy_percent,
        "medium": req.medium_percent,
        "hard": req.hard_percent
    }
    
    generated_json = gemini_service.generate_question_paper(
        board_name=board.board_name,
        class_name=classroom.class_name,
        subject_name=subject.subject_name,
        chapters=chapter_names,
        total_marks=total_marks,
        difficulty_dist=difficulty_dist,
        language=req.language,
        num_sets=req.num_sets,
        time_allowed=req.time_allowed_minutes,
        school_name=req.school_name,
        question_breakdown=req.question_breakdown,
        num_diagram_questions=req.num_diagram_questions
    )

    # 4. Save to Database
    paper_id = str(uuid.uuid4())
    paper_name = f"{classroom.class_name} {subject.subject_name} ({total_marks} Marks)"
    
    # Inject school name and metadata into JSON for rendering
    generated_json["school_name"] = req.school_name
    generated_json["board"] = board.board_name
    generated_json["class_name"] = classroom.class_name
    generated_json["subject"] = subject.subject_name
    generated_json["total_marks"] = total_marks
    generated_json["time_allowed_minutes"] = req.time_allowed_minutes
    generated_json["date"] = req.date if req.date else "29/12/24"
    if req.instructions is not None:
        generated_json["instructions"] = req.instructions
    if req.constants is not None:
        generated_json["constants"] = req.constants

    db_paper = GeneratedPaper(
        id=paper_id,
        paper_name=paper_name,
        paper_json=generated_json,
        created_by=current_user.id
    )
    
    db.add(db_paper)
    db.commit()
    db.refresh(db_paper)
    
    return db_paper

@router.delete("/{paper_id}", status_code=status.HTTP_200_OK)
def delete_paper(
    paper_id: str, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    paper = db.query(GeneratedPaper).filter(
        GeneratedPaper.id == paper_id, 
        GeneratedPaper.created_by == current_user.id
    ).first()
    
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found or unauthorized.")
        
    db.delete(paper)
    db.commit()
    return {"status": "success", "message": "Question paper deleted successfully."}

@router.get("/{paper_id}/pdf")
def download_paper_pdf(
    paper_id: str,
    set_char: str = "A",
    include_answers: bool = False,
    db: Session = Depends(get_db)
):
    """Generates PDF for the chosen set (A, B, C, D) and returns it as file download."""
    paper = db.query(GeneratedPaper).filter(GeneratedPaper.id == paper_id).first()
    if not paper:
        raise HTTPException(status_code=404, detail="Question paper not found.")
        
    try:
        # Create HTML string
        html_str = pdf_service.generate_html(
            paper_data=paper.paper_json,
            selected_set=set_char,
            include_answers=include_answers
        )
        
        # Render HTML to PDF
        pdf_bytes = pdf_service.render_pdf(html_str)
        
        # Format filename
        subject_slug = paper.paper_json.get("subject", "subject").replace(" ", "_")
        class_slug = paper.paper_json.get("class_name", "class").replace(" ", "_")
        doc_type = "AnswerKey" if include_answers else "QuestionPaper"
        filename = f"{class_slug}_{subject_slug}_Set_{set_char}_{doc_type}.pdf"
        
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"attachment; filename={filename}",
                "Access-Control-Expose-Headers": "Content-Disposition"
            }
        )
    except Exception as e:
        print(f"PDF Endpoint error: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate PDF question paper: {str(e)}"
        )

@router.put("/{paper_id}", response_model=PaperOut)
def update_saved_paper(
    paper_id: str,
    paper_json: dict = Body(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Updates the JSON configuration of a saved question paper."""
    paper = db.query(GeneratedPaper).filter(
        GeneratedPaper.id == paper_id,
        GeneratedPaper.created_by == current_user.id
    ).first()
    
    if not paper:
        raise HTTPException(status_code=404, detail="Question paper not found or unauthorized.")
        
    paper.paper_json = paper_json
    # Update paper name if class/subject/marks changed
    classroom = paper_json.get("class_name", "Class")
    subject = paper_json.get("subject", "Subject")
    total_marks = paper_json.get("total_marks", 20)
    paper.paper_name = f"{classroom} {subject} ({total_marks} Marks)"
    
    db.commit()
    db.refresh(paper)
    return paper

@router.post("/{paper_id}/regenerate-question", response_model=PaperOut)
def regenerate_paper_question(
    paper_id: str,
    payload: dict = Body(...), # expects {"set_char": "A", "section_idx": 0, "question_id": "q1"}
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Regenerates a single question in the question paper using Gemini AI."""
    paper = db.query(GeneratedPaper).filter(
        GeneratedPaper.id == paper_id,
        GeneratedPaper.created_by == current_user.id
    ).first()
    
    if not paper:
        raise HTTPException(status_code=404, detail="Question paper not found or unauthorized.")
        
    set_char = payload.get("set_char", "A")
    section_idx = payload.get("section_idx", 0)
    question_id = payload.get("question_id")
    
    paper_data = paper.paper_json
    sets = paper_data.get("sets", {})
    target_set = sets.get(set_char, {})
    sections = target_set.get("sections", [])
    
    if section_idx >= len(sections):
        raise HTTPException(status_code=400, detail="Invalid section index.")
        
    section = sections[section_idx]
    questions = section.get("questions", [])
    
    # Find the target question
    target_q = None
    q_index = -1
    for i, q in enumerate(questions):
        if q.get("id") == question_id:
            target_q = q
            q_index = i
            break
            
    if not target_q:
        raise HTTPException(status_code=404, detail="Question not found in the specified set/section.")
        
    # Get metadata for regeneration
    board_name = paper_data.get("board", "Maharashtra State Board")
    class_name = paper_data.get("class_name", "Class 10")
    subject_name = paper_data.get("subject", "Science")
    
    # Try to extract chapters or use chapter_name from the question
    chapter = target_q.get("chapter_name", "General")
    
    question_type = target_q.get("question_type", "Short Answer")
    marks = target_q.get("marks", 2)
    difficulty = target_q.get("difficulty", "medium")
    language = paper_data.get("language", "English")
    current_question_text = target_q.get("question_text", "")
    
    # Check if this question requires a diagram
    is_diagram = "diagram" in current_question_text.lower() or "draw" in current_question_text.lower()
    
    # Call Gemini to regenerate a single question
    new_q_data = gemini_service.regenerate_single_question(
        board_name=board_name,
        class_name=class_name,
        subject_name=subject_name,
        chapter=chapter,
        question_type=question_type,
        marks=marks,
        difficulty=difficulty,
        language=language,
        current_question_text=current_question_text,
        is_diagram=is_diagram
    )
    
    # Assign the same ID so the reference is kept
    new_q_data["id"] = question_id
    
    # Update question in place
    questions[q_index] = new_q_data
    
    # Also update the model answer in the answer key for this set
    answer_key = paper_data.get("answer_key", {})
    set_answers = answer_key.get(set_char, [])
    
    ans_index = -1
    for i, ans in enumerate(set_answers):
        if ans.get("id") == question_id:
            ans_index = i
            break
            
    new_ans = {
        "id": question_id,
        "model_answer": new_q_data.get("model_answer", "N/A"),
        "key_points": new_q_data.get("key_points", []),
        "marks": marks
    }
    
    if ans_index >= 0:
        set_answers[ans_index] = new_ans
    else:
        set_answers.append(new_ans)
        
    # Mark the session modified
    from sqlalchemy.orm.attributes import flag_modified
    paper.paper_json = paper_data
    flag_modified(paper, "paper_json")
    
    db.commit()
    db.refresh(paper)
    
    return paper
