'use client';

import { useEffect, useState } from 'react';
import { useAuthStore } from '@/store/useAuthStore';
import { usePaperStore } from '@/store/usePaperStore';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { 
  Sparkles, FileText, Trash2, Eye, Plus, Search, 
  Layers, GraduationCap, Calendar, AlertCircle
} from 'lucide-react';

export default function Dashboard() {
  const { user, token } = useAuthStore();
  const { savedPapers, fetchSavedPapers, deletePaper, loading } = usePaperStore();
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (!token && !localStorage.getItem('token')) {
      router.push('/login');
    } else {
      fetchSavedPapers();
    }
  }, [token, router, fetchSavedPapers]);

  const handleDelete = async (id: string, e: React.MouseEvent) => {
    e.preventDefault();
    if (confirm('Are you sure you want to delete this question paper?')) {
      await deletePaper(id);
    }
  };

  const filteredPapers = savedPapers.filter((paper) => 
    paper.paper_name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-8">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-gradient-to-r from-indigo-950/20 via-purple-950/15 to-transparent p-8 rounded-2xl border border-indigo-500/10">
        <div>
          <h2 className="text-3xl font-extrabold text-white tracking-tight">
            Hello, {user?.name || 'Educator'}!
          </h2>
          <p className="text-slate-400 text-sm mt-1">
            Generate and manage your Maharashtra State Board question papers here.
          </p>
        </div>
        <Link
          href="/generate"
          className="px-5 py-3 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white font-semibold text-sm transition-all duration-200 flex items-center gap-2 shadow-lg shadow-indigo-500/20 cursor-pointer"
        >
          <Plus className="w-4.5 h-4.5" /> Generate Exam Paper
        </Link>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="glass-card p-6 rounded-2xl space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-indigo-400">Total Papers</p>
          <h3 className="text-4xl font-extrabold text-white">{savedPapers.length}</h3>
          <p className="text-[10px] text-slate-500 font-medium">Generated by you</p>
        </div>
        <div className="glass-card p-6 rounded-2xl space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-purple-400">Class Supported</p>
          <h3 className="text-4xl font-extrabold text-white">Class 10</h3>
          <p className="text-[10px] text-slate-500 font-medium">Maharashtra State Board</p>
        </div>
        <div className="glass-card p-6 rounded-2xl space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-pink-400">Subject Coverage</p>
          <h3 className="text-4xl font-extrabold text-white">Science</h3>
          <p className="text-[10px] text-slate-500 font-medium">Auto RAG matched</p>
        </div>
      </div>

      {/* Main Section */}
      <div className="space-y-5">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <h3 className="text-lg font-bold text-white">Your Saved Papers</h3>
          
          {/* Search bar */}
          <div className="relative w-full sm:w-80">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
            <input
              type="text"
              placeholder="Search exam papers..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-slate-900/40 border border-slate-800 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500 transition-all"
            />
          </div>
        </div>

        {/* Papers Listing */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="glass-card h-40 rounded-2xl shimmer-loader opacity-60" />
            ))}
          </div>
        ) : filteredPapers.length === 0 ? (
          <div className="glass-card p-12 rounded-2xl text-center flex flex-col items-center justify-center space-y-4">
            <AlertCircle className="w-12 h-12 text-slate-600" />
            <div>
              <h4 className="font-bold text-white">No Exam Papers Found</h4>
              <p className="text-slate-400 text-xs mt-1">
                {searchQuery ? 'Try matching a different search keyword.' : 'Get started by generating your first exam paper!'}
              </p>
            </div>
            {!searchQuery && (
              <Link
                href="/generate"
                className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold transition-colors"
              >
                Create Paper
              </Link>
            )}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {filteredPapers.map((paper) => (
              <Link 
                href={`/preview/${paper.id}`}
                key={paper.id} 
                className="glass-card p-6 rounded-2xl flex flex-col justify-between h-44 group cursor-pointer"
              >
                <div className="space-y-3">
                  <div className="flex justify-between items-start">
                    <h4 className="font-bold text-base text-white group-hover:text-indigo-400 transition-colors leading-snug line-clamp-1">
                      {paper.paper_name}
                    </h4>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <span className="px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-400 text-[10px] font-semibold border border-indigo-500/20">
                      {paper.paper_json?.board || 'MSBSHSE'}
                    </span>
                    <span className="px-2 py-0.5 rounded bg-purple-500/10 text-purple-400 text-[10px] font-semibold border border-purple-500/20">
                      Class: {paper.paper_json?.class_name || '10'}
                    </span>
                    <span className="px-2 py-0.5 rounded bg-pink-500/10 text-pink-400 text-[10px] font-semibold border border-pink-500/20">
                      Marks: {paper.paper_json?.total_marks || '40'}
                    </span>
                  </div>
                </div>

                <div className="flex justify-between items-center pt-4 border-t border-slate-900 text-xs text-slate-500">
                  <div className="flex items-center gap-1.5">
                    <Calendar className="w-3.5 h-3.5 text-slate-600" />
                    <span>{new Date(paper.created_at).toLocaleDateString()}</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-[10px] font-semibold text-slate-400 flex items-center gap-1 hover:text-white transition-colors">
                      <Eye className="w-3.5 h-3.5" /> View
                    </span>
                    <button
                      onClick={(e) => handleDelete(paper.id, e)}
                      className="text-[10px] font-semibold text-slate-400 flex items-center gap-1 hover:text-red-400 transition-colors cursor-pointer"
                    >
                      <Trash2 className="w-3.5 h-3.5" /> Delete
                    </button>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
